name: Publish

on:
  push:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  build:
    uses: MinecraftForge/SharedActions/.github/workflows/gradle.yml@main
    with:
      java: 8
      gradle_tasks: "publish"
      artifact_name: "installer"
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      PROMOTE_ARTIFACT_WEBHOOK: ${{ secrets.PROMOTE_ARTIFACT_WEBHOOK }}
      PROMOTE_ARTIFACT_USERNAME: ${{ secrets.PROMOTE_ARTIFACT_USERNAME }}
      PROMOTE_ARTIFACT_PASSWORD: ${{ secrets.PROMOTE_ARTIFACT_PASSWORD }}
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
